cluster stop in dist

diff --git a/dist/bin/kctf-cluster b/dist/bin/kctf-cluster
--- a/dist/bin/kctf-cluster
+++ b/dist/bin/kctf-cluster
@@ -14,21 +14,138 @@
 # limitations under the License.
 set -Eeuo pipefail
 
+function kctf_cluster_start {
+  MIN_NODES="1"
+  MAX_NODES="2"
+  NUM_NODES="1"
+  MACHINE_TYPE="n2-standard-4"
+
+  EXISTING_CLUSTER=$(gcloud container clusters list --filter "name=${CLUSTER_NAME}" --format 'get(name)')
+
+  if [ -z "${EXISTING_CLUSTER}" ]; then
+    gcloud container clusters create --release-channel=regular --enable-network-policy --enable-autoscaling --min-nodes ${MIN_NODES} --max-nodes ${MAX_NODES} --num-nodes ${NUM_NODES} --create-subnetwork name=kctf-${CLUSTER_NAME}-subnet --no-enable-master-authorized-networks --enable-ip-alias --enable-private-nodes --master-ipv4-cidr 172.16.0.32/28 --enable-autorepair --preemptible --machine-type ${MACHINE_TYPE} --workload-pool=${PROJECT}.svc.id.goog ${CLUSTER_NAME}
+  fi
+
+  EXISTING_ROUTER=$(gcloud compute routers list --filter "name=kctf-${CLUSTER_NAME}-nat-router" --format 'get(name)')
+  if [ -z "${EXISTING_ROUTER}" ]; then
+    gcloud compute routers create "kctf-${CLUSTER_NAME}-nat-router" --network=default --region "${ZONE::-2}"
+  fi
+
+  EXISTING_NAT=$(gcloud compute routers nats list --router "kctf-${CLUSTER_NAME}-nat-router" --router-region "${ZONE::-2}" --format 'get(name)')
+  if [ -z "${EXISTING_NAT}" ]; then
+    gcloud compute routers nats create "kctf-${CLUSTER_NAME}-nat-config" --router-region "${ZONE::-2}" --router kctf-${CLUSTER_NAME}-nat-router --nat-all-subnet-ip-ranges --auto-allocate-nat-external-ips
+  fi
+
+  kubectl create namespace "kctf-system" --dry-run=client -oyaml | kubectl apply -f - >&2
+
+  # GCSFUSE
+
+  SUFFIX=$(echo "${PROJECT}-${CLUSTER_NAME}-${ZONE}" | sha1sum)
+  BUCKET_NAME="kctf-gcsfuse-${SUFFIX:0:16}"
+  GCS_GSA_NAME="${BUCKET_NAME}"
+  GCS_GSA_EMAIL=$(gcloud iam service-accounts list --filter "email=${GCS_GSA_NAME}@${PROJECT}.iam.gserviceaccount.com" --format 'get(email)' || true)
+
+  if [ -z "${GCS_GSA_EMAIL}" ]; then
+    gcloud iam service-accounts create "${GCS_GSA_NAME}" --description "kCTF GCSFUSE service account ${CLUSTER_NAME} ${ZONE}" --display-name "kCTF GCSFUSE ${CLUSTER_NAME} ${ZONE}"
+    GCS_GSA_EMAIL=$(gcloud iam service-accounts list --filter "email=${GCS_GSA_NAME}@${PROJECT}.iam.gserviceaccount.com" --format 'get(email)')
+    while [ -z "${GCS_GSA_EMAIL}" ]; do
+      sleep 1
+      GCS_GSA_EMAIL=$(gcloud iam service-accounts list --filter "email=${GCS_GSA_NAME}@${PROJECT}.iam.gserviceaccount.com" --format 'get(email)')
+    done
+  fi
+
+  # Creating CRD, rbac and operator
+  kubectl apply -f "${KCTF_CTF_DIR}/kctf/resources/kctf.dev_challenges_crd.yaml"
+  kubectl apply -f "${KCTF_CTF_DIR}/kctf/resources/rbac.yaml"
+  kubectl apply -f "${KCTF_CTF_DIR}/kctf/resources/operator.yaml"
+
+  OPERATOR_IMAGE=$("${KCTF_BIN}/yq" eval '.spec.template.spec.containers[0].image' "${KCTF_CTF_DIR}/kctf/resources/operator.yaml")
+
+  # The operator needs to create some subresources, e.g. the gcsfuse service account
+  for i in {1..30}; do
+    kubectl get pods --namespace kctf-system -o=jsonpath="{.items[*].status.containerStatuses[?(@.image==\"${OPERATOR_IMAGE}\")].ready}" | grep "true" && break
+    if [ "$i" == "30" ]; then
+      echo "Couldn't find a kctf-operator pod with status ready=true and image=\"${OPERATOR_IMAGE}\" after 5 minutes" >&2
+      kubectl get pods --namespace kctf-system -o=yaml >&2
+      exit 1
+    fi
+    sleep 10
+  done
+
+  GCS_KSA_NAME="gcsfuse-sa"
+
+  gcloud iam service-accounts add-iam-policy-binding --role roles/iam.workloadIdentityUser --member "serviceAccount:${PROJECT}.svc.id.goog[kctf-system/${GCS_KSA_NAME}]" ${GCS_GSA_EMAIL}
+  kubectl annotate serviceaccount --namespace kctf-system ${GCS_KSA_NAME} iam.gke.io/gcp-service-account=${GCS_GSA_EMAIL} --overwrite
+
+  if ! gsutil du "gs://${BUCKET_NAME}/"; then
+    gsutil mb -l eu "gs://${BUCKET_NAME}/"
+  fi
+
+  if gsutil uniformbucketlevelaccess get "gs://${BUCKET_NAME}" | grep -q "Enabled: True"; then
+    gsutil iam ch "serviceAccount:${GCS_GSA_EMAIL}:roles/storage.legacyBucketOwner" "gs://${BUCKET_NAME}"
+    gsutil iam ch "serviceAccount:${GCS_GSA_EMAIL}:roles/storage.legacyObjectOwner" "gs://${BUCKET_NAME}"
+  else
+    gsutil acl ch -u "${GCS_GSA_EMAIL}:O" "gs://${BUCKET_NAME}"
+  fi
+
+  kubectl create configmap gcsfuse-config --from-literal=gcs_bucket="${BUCKET_NAME}" --namespace kctf-system --dry-run=client -o yaml | kubectl apply -f -
+
+  kubectl patch ServiceAccount default --patch "automountServiceAccountToken: false"
+
+  # Cloud DNS
+
+  if [ ! -z "${DOMAIN_NAME}" ]
+  then
+    DNS_ZONE=$(gcloud dns managed-zones list --filter "dns_name:${DOMAIN_NAME}" --format 'get(name)')
+    if [ -z "${DNS_ZONE}" ]; then
+      gcloud dns managed-zones create "${CLUSTER_NAME}-dns-zone" --description "DNS Zone for ${DOMAIN_NAME}" --dns-name="${DOMAIN_NAME}."
+    fi
+
+    DNS_GSA_NAME="kctf-cloud-dns"
+    DNS_GSA_EMAIL=$(gcloud iam service-accounts list --filter "email=${DNS_GSA_NAME}@${PROJECT}.iam.gserviceaccount.com" --format 'get(email)' || true)
+
+    if [ -z "${DNS_GSA_EMAIL}" ]; then
+      gcloud iam service-accounts create "${DNS_GSA_NAME}" --description "kCTF Cloud DNS service account ${CLUSTER_NAME} ${ZONE}" --display-name "kCTF Cloud DNS ${CLUSTER_NAME} ${ZONE}"
+      DNS_GSA_EMAIL=$(gcloud iam service-accounts list --filter "email=${DNS_GSA_NAME}@${PROJECT}.iam.gserviceaccount.com" --format 'get(email)')
+      while [ -z "${DNS_GSA_EMAIL}" ]; do
+        sleep 1
+        DNS_GSA_EMAIL=$(gcloud iam service-accounts list --filter "email=${DNS_GSA_NAME}@${PROJECT}.iam.gserviceaccount.com" --format 'get(email)')
+      done
+    fi
+
+    DNS_KSA_NAME="external-dns-sa"
+
+    gcloud iam service-accounts add-iam-policy-binding --role roles/iam.workloadIdentityUser --member "serviceAccount:${PROJECT}.svc.id.goog[kctf-system/${DNS_KSA_NAME}]" ${DNS_GSA_EMAIL}
+    kubectl annotate serviceaccount --namespace kctf-system ${DNS_KSA_NAME} iam.gke.io/gcp-service-account=${DNS_GSA_EMAIL} --overwrite
+
+    gcloud projects add-iam-policy-binding ${PROJECT} --member=serviceAccount:${DNS_GSA_EMAIL} --role=roles/dns.admin
+
+    kubectl create configmap --namespace kctf-system external-dns --from-literal=DOMAIN_NAME=${DOMAIN_NAME} --dry-run=client -o yaml | kubectl apply -f -
+  fi
+}
+
+function kctf_cluster_stop {
+  CLOUDSDK_CORE_DISABLE_PROMPTS=1 gcloud container clusters delete ${CLUSTER_NAME}
+  gcloud compute routers delete "kctf-${CLUSTER_NAME}-nat-router" --region "${ZONE::-2}" --quiet
+
+  SUFFIX=$(echo "${PROJECT}-${CLUSTER_NAME}-${ZONE}" | sha1sum)
+  GSA_NAME="kctf-gcsfuse-${SUFFIX:0:16}"
+  GSA_EMAIL=$(gcloud iam service-accounts list --filter "email=${GSA_NAME}@${PROJECT}.iam.gserviceaccount.com" --format 'get(email)' || true)
+  if [ -z "${GSA_EMAIL}" ]; then
+    gcloud iam service-accounts delete "${GSA_EMAIL}"
+  fi
+}
+
 function kctf_cluster_usage {
   echo "kctf cluster command" 2>&1
   echo -e "\tavailable commands:" 2>&1
   echo -e "\t\tstart:\tstart the cluster" 2>&1
+  echo -e "\t\tstop:\tstop the cluster" 2>&1
 }
 
-if [[ $# -ne 1 ]]; then
+if [[ $# -lt 1 ]]; then
   echo "unexpected argument count" >&2
-  kctf_cluster_usage
-  exit 1
-fi
-
-if [[ $1 != "start" ]]; then
-  echo "unknown command" >&2
-  kctf_cluster_usage
+  kctf_chal_usage
   exit 1
 fi
 
@@ -37,110 +154,19 @@ if [[ -z "${CLUSTER_NAME-}" ]]; then
   exit 1
 fi
 
-MIN_NODES="1"
-MAX_NODES="2"
-NUM_NODES="1"
-MACHINE_TYPE="n2-standard-4"
-
-EXISTING_CLUSTER=$(gcloud container clusters list --filter "name=${CLUSTER_NAME}" --format 'get(name)')
-
-if [ -z "${EXISTING_CLUSTER}" ]; then
-  gcloud container clusters create --release-channel=regular --enable-network-policy --enable-autoscaling --min-nodes ${MIN_NODES} --max-nodes ${MAX_NODES} --num-nodes ${NUM_NODES} --create-subnetwork name=kctf-${CLUSTER_NAME}-subnet --no-enable-master-authorized-networks --enable-ip-alias --enable-private-nodes --master-ipv4-cidr 172.16.0.32/28 --enable-autorepair --preemptible --machine-type ${MACHINE_TYPE} --workload-pool=${PROJECT}.svc.id.goog ${CLUSTER_NAME}
-fi
-
-EXISTING_ROUTER=$(gcloud compute routers list --filter "name=kctf-${CLUSTER_NAME}-nat-router" --format 'get(name)')
-if [ -z "${EXISTING_ROUTER}" ]; then
-  gcloud compute routers create "kctf-${CLUSTER_NAME}-nat-router" --network=default --region "${ZONE::-2}"
-fi
-
-EXISTING_NAT=$(gcloud compute routers nats list --router "kctf-${CLUSTER_NAME}-nat-router" --router-region "${ZONE::-2}" --format 'get(name)')
-if [ -z "${EXISTING_NAT}" ]; then
-  gcloud compute routers nats create "kctf-${CLUSTER_NAME}-nat-config" --router-region "${ZONE::-2}" --router kctf-${CLUSTER_NAME}-nat-router --nat-all-subnet-ip-ranges --auto-allocate-nat-external-ips
-fi
-
-kubectl create namespace "kctf-system" --dry-run=client -oyaml | kubectl apply -f - >&2
-
-# GCSFUSE
-
-SUFFIX=$(echo "${PROJECT}-${CLUSTER_NAME}-${ZONE}" | sha1sum)
-BUCKET_NAME="kctf-gcsfuse-${SUFFIX:0:16}"
-GCS_GSA_NAME="${BUCKET_NAME}"
-GCS_GSA_EMAIL=$(gcloud iam service-accounts list --filter "email=${GCS_GSA_NAME}@${PROJECT}.iam.gserviceaccount.com" --format 'get(email)' || true)
-
-if [ -z "${GCS_GSA_EMAIL}" ]; then
-  gcloud iam service-accounts create "${GCS_GSA_NAME}" --description "kCTF GCSFUSE service account ${CLUSTER_NAME} ${ZONE}" --display-name "kCTF GCSFUSE ${CLUSTER_NAME} ${ZONE}"
-  GCS_GSA_EMAIL=$(gcloud iam service-accounts list --filter "email=${GCS_GSA_NAME}@${PROJECT}.iam.gserviceaccount.com" --format 'get(email)')
-  while [ -z "${GCS_GSA_EMAIL}" ]; do
-    sleep 1
-    GCS_GSA_EMAIL=$(gcloud iam service-accounts list --filter "email=${GCS_GSA_NAME}@${PROJECT}.iam.gserviceaccount.com" --format 'get(email)')
-  done
-fi
-
-# Creating CRD, rbac and operator
-kubectl apply -f "${KCTF_CTF_DIR}/kctf/resources/kctf.dev_challenges_crd.yaml"
-kubectl apply -f "${KCTF_CTF_DIR}/kctf/resources/rbac.yaml"
-kubectl apply -f "${KCTF_CTF_DIR}/kctf/resources/operator.yaml"
-
-OPERATOR_IMAGE=$("${KCTF_BIN}/yq" eval '.spec.template.spec.containers[0].image' "${KCTF_CTF_DIR}/kctf/resources/operator.yaml")
-
-# The operator needs to create some subresources, e.g. the gcsfuse service account
-for i in {1..30}; do
-  kubectl get pods --namespace kctf-system -o=jsonpath="{.items[*].status.containerStatuses[?(@.image==\"${OPERATOR_IMAGE}\")].ready}" | grep "true" && break
-  if [ "$i" == "30" ]; then
-    echo "Couldn't find a kctf-operator pod with status ready=true and image=\"${OPERATOR_IMAGE}\" after 5 minutes" >&2
-    kubectl get pods --namespace kctf-system -o=yaml >&2
+case "$1" in
+  start)
+    shift
+    kctf_cluster_start $@
+    ;;
+  stop)
+    shift
+    kctf_cluster_stop $@
+    ;;
+  *)
+    echo "unknown command" >&2
+    kctf_cluster_usage
     exit 1
-  fi
-  sleep 10
-done
+    ;;
+esac
 
-GCS_KSA_NAME="gcsfuse-sa"
-
-gcloud iam service-accounts add-iam-policy-binding --role roles/iam.workloadIdentityUser --member "serviceAccount:${PROJECT}.svc.id.goog[kctf-system/${GCS_KSA_NAME}]" ${GCS_GSA_EMAIL}
-kubectl annotate serviceaccount --namespace kctf-system ${GCS_KSA_NAME} iam.gke.io/gcp-service-account=${GCS_GSA_EMAIL} --overwrite
-
-if ! gsutil du "gs://${BUCKET_NAME}/"; then
-  gsutil mb -l eu "gs://${BUCKET_NAME}/"
-fi
-
-if gsutil uniformbucketlevelaccess get "gs://${BUCKET_NAME}" | grep -q "Enabled: True"; then
-  gsutil iam ch "serviceAccount:${GCS_GSA_EMAIL}:roles/storage.legacyBucketOwner" "gs://${BUCKET_NAME}"
-  gsutil iam ch "serviceAccount:${GCS_GSA_EMAIL}:roles/storage.legacyObjectOwner" "gs://${BUCKET_NAME}"
-else
-  gsutil acl ch -u "${GCS_GSA_EMAIL}:O" "gs://${BUCKET_NAME}"
-fi
-
-kubectl create configmap gcsfuse-config --from-literal=gcs_bucket="${BUCKET_NAME}" --namespace kctf-system --dry-run=client -o yaml | kubectl apply -f -
-
-kubectl patch ServiceAccount default --patch "automountServiceAccountToken: false"
-
-# Cloud DNS
-
-if [ ! -z "${DOMAIN_NAME}" ]
-then
-  DNS_ZONE=$(gcloud dns managed-zones list --filter "dns_name:${DOMAIN_NAME}" --format 'get(name)')
-  if [ -z "${DNS_ZONE}" ]; then
-    gcloud dns managed-zones create "${CLUSTER_NAME}-dns-zone" --description "DNS Zone for ${DOMAIN_NAME}" --dns-name="${DOMAIN_NAME}."
-  fi
-
-  DNS_GSA_NAME="kctf-cloud-dns"
-  DNS_GSA_EMAIL=$(gcloud iam service-accounts list --filter "email=${DNS_GSA_NAME}@${PROJECT}.iam.gserviceaccount.com" --format 'get(email)' || true)
-
-  if [ -z "${DNS_GSA_EMAIL}" ]; then
-    gcloud iam service-accounts create "${DNS_GSA_NAME}" --description "kCTF Cloud DNS service account ${CLUSTER_NAME} ${ZONE}" --display-name "kCTF Cloud DNS ${CLUSTER_NAME} ${ZONE}"
-    DNS_GSA_EMAIL=$(gcloud iam service-accounts list --filter "email=${DNS_GSA_NAME}@${PROJECT}.iam.gserviceaccount.com" --format 'get(email)')
-    while [ -z "${DNS_GSA_EMAIL}" ]; do
-      sleep 1
-      DNS_GSA_EMAIL=$(gcloud iam service-accounts list --filter "email=${DNS_GSA_NAME}@${PROJECT}.iam.gserviceaccount.com" --format 'get(email)')
-    done
-  fi
-
-  DNS_KSA_NAME="external-dns-sa"
-
-  gcloud iam service-accounts add-iam-policy-binding --role roles/iam.workloadIdentityUser --member "serviceAccount:${PROJECT}.svc.id.goog[kctf-system/${DNS_KSA_NAME}]" ${DNS_GSA_EMAIL}
-  kubectl annotate serviceaccount --namespace kctf-system ${DNS_KSA_NAME} iam.gke.io/gcp-service-account=${DNS_GSA_EMAIL} --overwrite
-
-  gcloud projects add-iam-policy-binding ${PROJECT} --member=serviceAccount:${DNS_GSA_EMAIL} --role=roles/dns.admin
-
-  kubectl create configmap --namespace kctf-system external-dns --from-literal=DOMAIN_NAME=${DOMAIN_NAME} --dry-run=client -o yaml | kubectl apply -f -
-fi
diff --git a/dist/bin/kctf-config b/dist/bin/kctf-config
--- a/dist/bin/kctf-config
+++ b/dist/bin/kctf-config
@@ -41,7 +41,10 @@ function _kctf_config_load {
   source "${CONFIG_PATH}" || return 1
   if command -v gcloud >/dev/null 2>&1; then
     echo "Updating gcloud config."
-    _kctf_update_gcloud_config || return 1
+    if ! _kctf_update_gcloud_config; then
+      echo "Failed updating gcloud config" >&2
+      return 1
+    fi
   else
     echo "Configuration created only locally. Gcloud not installed." >&2
   fi
@@ -50,6 +53,8 @@ function _kctf_config_load {
 
   # try to fetch the creds of the k8s cluster
   _kctf_get_cluster_creds >/dev/null 2>/dev/null
+
+  echo "loaded config"
 
   KCTF_CONFIG="${CONFIG_NAME}"
 }
