challenge create in dist

diff --git a/dist/bin/kctf-challenge b/dist/bin/kctf-challenge
--- a/dist/bin/kctf-challenge
+++ b/dist/bin/kctf-challenge
@@ -21,16 +21,34 @@ function require_cluster_config {
   fi
 }
 
+function kctf_chal_create_usage {
+  echo "kctf chal create name" 2>&1
+}
+
+function kctf_chal_create {
+  if [[ $# -ne 1 ]]; then
+    echo "kctf chal create: name missing" >&2
+    kctf_chal_create_usage
+    exit 1
+  fi
+
+  CHALLENGE_NAME="$1"
+  shift
+
+  CHALLENGE_DIR="${KCTF_CTF_DIR}/${CHALLENGE_NAME}"
+  if [[ -e "${CHALLENGE_DIR}" ]]; then
+    exit 1
+  fi
+
+  umask a+rx
+  cp -p -r "${KCTF_CTF_DIR}/kctf/challenge-templates/challenge-skeleton" "${CHALLENGE_DIR}"
+  ${KCTF_BIN}/yq eval ".metadata.name = \"${CHALLENGE_NAME}\"" --inplace "${CHALLENGE_DIR}/challenge.yaml"
+}
+
 function kctf_chal_make_usage {
   echo "kctf chal make [args] target" 2>&1
   echo -e "args:" 2>&1
   echo -e "\t--challenge-name\tname of the challenge (defaults to the current directory)" >&2
-}
-
-function kctf_chal_usage {
-  echo "kctf chal command" 2>&1
-  echo -e "\tavailable commands:" 2>&1
-  echo -e "\t\tmake:\t(tmp) run commands from the Makefile" 2>&1
 }
 
 function kctf_chal_make {
@@ -39,7 +57,7 @@ function kctf_chal_make {
   PARSED=$(getopt --options=$OPTS --longoptions=$LONGOPTS --name "kctf chal create" -- "$@")
   if [[ $? -ne 0 ]]; then
     kctf_chal_make_usage
-    return 1
+    exit 1
   fi
   eval set -- "$PARSED"
 
@@ -65,7 +83,7 @@ function kctf_chal_make {
   if [[ $# -ne 1 ]]; then
     echo "kctf chal make: target missing" >&2
     kctf_chal_make_usage
-    return 1
+    exit 1
   fi
 
   TARGET="$1"
@@ -85,6 +103,12 @@ function kctf_chal_make {
   make -C "${CHALLENGE_PATH}" -f "${KCTF_CTF_DIR}/kctf/Makefile" "${TARGET}"
 }
 
+function kctf_chal_usage {
+  echo "kctf chal command" 2>&1
+  echo -e "\tavailable commands:" 2>&1
+  echo -e "\t\tmake:\t(tmp) run commands from the Makefile" 2>&1
+}
+
 if [[ $# -lt 1 ]]; then
   echo "unexpected argument count" >&2
   kctf_chal_usage
@@ -92,6 +116,10 @@ if [[ $# -lt 1 ]]; then
 fi
 
 case "$1" in
+  create)
+    shift
+    kctf_chal_create $@
+    ;;
   make)
     shift
     kctf_chal_make $@
