only require --domain-name for type=gce

diff --git a/dist/bin/kctf-config b/dist/bin/kctf-config
--- a/dist/bin/kctf-config
+++ b/dist/bin/kctf-config
@@ -105,14 +105,14 @@ function kctf_config_create_usage {
   echo "  -h|--help       print this help" >&2
   echo "  --type          what kind of cluster to create " >&2
   echo "                  currently supported values: gce (remote) and kind (local)" >&2
-  echo "  --project       Google Cloud Platform project name" >&2
+  echo "  --project       Required (gce): Google Cloud Platform project name" >&2
   echo "  --zone          GCP Zone (default: europe-west4-b)" >&2
   echo "                  For a list of zones run:" >&2
   echo "                    gcloud compute machine-types list --filter=\"name=( n2-standard-4 )\" --format 'value(zone)'" >&2
   echo "  --registry      Container Registry (default: eu.gcr.io)" >&2
   echo "                  Possible values are us.gcr.io, asia.gcr.io, and eu.gcr.io" >&2
   echo "  --cluster-name  Name of the kubernetes cluster (default: kctf-cluster)" >&2
-  echo "  --domain-name   Required: domain name to host challenges under" >&2
+  echo "  --domain-name   Required (gce): domain name to host challenges under" >&2
   echo "                  Please make sure not to put anything secret in the challenge name." >&2
   echo "                  Supported options:" >&2
   echo "                    \"none\": disable DNS support (might break some functionality)" >&2
@@ -195,16 +195,6 @@ function kctf_config_create {
     esac
   done
 
-  if [[ -z "${DOMAIN_NAME}" ]]; then
-    _kctf_log_err "kctf config create: --domain-name required"
-    kctf_config_create_usage
-    return 1
-  fi
-
-  if [[ "${DOMAIN_NAME}" == "none" ]]; then
-    DOMAIN_NAME=""
-  fi
-
   if [[ $# -ne 1 ]]; then
     _kctf_log_err "kctf config create: config name missing"
     kctf_config_create_usage
@@ -229,6 +219,11 @@ function kctf_config_create {
         kctf_config_create_usage
         return 1
       fi
+      if [[ -z "${DOMAIN_NAME}" ]]; then
+        _kctf_log_err "Missing required argument \"--domain-name\"."
+        kctf_config_create_usage
+        return 1
+      fi
       ;;
     kind)
       ;;
@@ -237,6 +232,11 @@ function kctf_config_create {
       return 1
       ;;
   esac
+
+  if [[ "${DOMAIN_NAME}" == "none" ]]; then
+    DOMAIN_NAME=""
+  fi
+
 
   mkdir -p "${KCTF_CTF_DIR}/kctf/config"
 
