if port-forward fails, retry with a random port

diff --git a/base/Makefile b/base/Makefile
--- a/base/Makefile
+++ b/base/Makefile
@@ -97,10 +97,21 @@ healthcheck-ssh: .cluster-config
 
 port-forward: .cluster-config
 	@PORT=31337
-	@kubectl port-forward deployment/${CHALLENGE_NAME} --address=127.0.0.1 $${PORT}:1337 > /dev/null &
-	@PORT_FORWARD_PID="$$!"
-	@PS1="\e[0;32m[kctf port-forward] \e[0;31m${CHALLENGE_NAME}@localhost:$${PORT}\e[m$$" bash --norc || true
-	@kill -15 $${PORT_FORWARD_PID}
+	@for i in {1..3}; do
+	@  kubectl port-forward deployment/${CHALLENGE_NAME} --address=127.0.0.1 $${PORT}:1337 > /dev/null &
+	@  PORT_FORWARD_PID="$$!"
+	@  sleep 1
+	@  if ! kill -0 "$${PORT_FORWARD_PID}" 2>/dev/null; then
+	@    if [ $$i == 3 ]; then
+	@      echo "port-forward failed 3 times, maybe the challenge is not running?" && false
+	@    fi
+	@    PORT=$$((1024+$$RANDOM))
+	@    continue
+	@  fi
+	@  PS1="\e[0;32m[kctf port-forward] \e[0;31m${CHALLENGE_NAME}@localhost:$${PORT}\e[m$$" bash --norc || true
+	@  kill -15 $${PORT_FORWARD_PID}
+	@  break
+	@done
 
 test-docker: .gen/docker-id
 	docker ps -f "id=$$(cat .gen/docker-id)"
