Clean up kctf-conf/base (#179)
* move config/docker to docker-images

* prebuild challenge and healthcheck image

* don't build nsjail and healthcheck image in makefile anymore

* update skeleton healthcheck image

* update samples

* fix docker image name in workflow

* mount resolv.conf in nsjail

* rename maybe_pow.py to kctf_pow

* no need to use a venv for pwntools anymore

* remove broken symlink

* remove challenge skeleton from base

* fix chroot setup

* s/drop_privs/kctf_drop_privs/

* add dev null to chroot

* yq update to v4 changed everything and no way to install old version from snap :(

* Automated commit: update images.

Co-authored-by: Stephen Roettger <stephen.roettger@gmail.com>

diff --git a/docker-images/challenge/kctf_pow b/docker-images/challenge/kctf_pow
--- a/docker-images/challenge/kctf_pow
+++ b/docker-images/challenge/kctf_pow
@@ -1,3 +1,4 @@
+#!/bin/bash
 # Copyright 2020 Google LLC
 # 
 # Licensed under the Apache License, Version 2.0 (the "License");
@@ -11,12 +12,15 @@
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
-.PHONY: docker .FORCE
 
-docker: .gen/docker-image
+POW_FILE="/kctf/pow/pow.conf"
 
-.gen/docker-image: .FORCE
-	docker build -t "kctf-nsjail" .
-	echo $$(docker image ls "kctf-nsjail" -q) > $@
+if [ -f ${POW_FILE} ]; then
+  POW="$(cat ${POW_FILE})"
+  if ! /kctf/pow.py ask "${POW}"; then
+    echo 'pow fail'
+    exit 1
+  fi
+fi
 
-.FORCE:
+exec "$@"
